name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Puedes cambiar a la versión que necesites

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Asegúrate de tener un requirements.txt

    - name: Run the Python script
      run: python aspen.py  # Cambia 'your_script.py' por el nombre de tu archivo
