name: Python CI

on:
  schedule:
    - cron: '*/21600 * * * *'  # Se ejecuta cada 5 minutos 

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 horas

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the Python script
      run: |
        python blue.py || { echo 'Script failed. Exiting.'; exit 1; }
