name: Python CI

on:
  schedule:
    - cron: '0 */6 * * *'  # Se ejecuta cada 6 horas

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 horas

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the Python script
      run: |
        python blue.py || { echo 'Script failed. Exiting.'; exit 1; }
